/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-02-05 13:55:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.naming.InitialContext;
import javax.naming.InitialContext;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

public final class check_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("javax.naming.InitialContext");
    _jspx_imports_classes.add("javax.sql.DataSource");
    _jspx_imports_classes.add("javax.naming.Context");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("  * 동국대학교 베팅형 수강신청 \r\n");
      out.write("  * check.jsp\r\n");
      out.write("  * 수강신청 확인 페이지\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>동국대학교 서울캠퍼스 수강신청</title>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"form\").show(\"slow\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#tip\").hover(function(){\r\n");
      out.write("\t  $(\"#div2\").show(\"slow\");\r\n");
      out.write("\t  $(\"#tip\").css('background-color', '#43A047');\r\n");
      out.write("\t\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t  $(\"#div2\").slideUp(\"slow\");\r\n");
      out.write("\t  $(\"#tip\").css('background-color', '#ff7f00');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#bbb1\").hover(function(){\t  \r\n");
      out.write("\t\t  $(\"#bbb1\").css('background-color', '#43A047');\r\n");
      out.write("\t\t},function(){\t \r\n");
      out.write("\t\t  $(\"#bbb1\").css('background-color', '#ff7f00');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#bbb2\").hover(function(){\t  \r\n");
      out.write("\t\t  $(\"#bbb2\").css('background-color', '#43A047');\r\n");
      out.write("\t\t},function(){\t \r\n");
      out.write("\t\t  $(\"#bbb2\").css('background-color', '#ff7f00');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#bbb3\").hover(function(){\t  \r\n");
      out.write("\t\t  $(\"#bbb3\").css('background-color', '#43A047');\r\n");
      out.write("\t\t},function(){\t \r\n");
      out.write("\t\t  $(\"#bbb3\").css('background-color', '#ff7f00');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#bbb4\").hover(function(){\t  \r\n");
      out.write("\t\t  $(\"#bbb4\").css('background-color', '#43A047');\r\n");
      out.write("\t\t},function(){\t \r\n");
      out.write("\t\t  $(\"#bbb4\").css('background-color', '#ff7f00');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type = \"text/css\">\r\n");
      out.write("\t\t/* 배경화면을 꽉차게 설정 */\r\n");
      out.write("\t    html {\r\n");
      out.write("\t\t\tbackground: url(\"res/background.gif\") no-repeat center center fixed;\r\n");
      out.write("\t        -webkit-background-size: cover;\r\n");
      out.write("\t        -moz-background-size: cover;\r\n");
      out.write("\t        -o-background-size: cover;\r\n");
      out.write("\t        background-size: cover;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t       \r\n");
      out.write("\t\tdiv.fixed {\r\n");
      out.write("\t\t\t-webkit-background-size: cover;\r\n");
      out.write("\t        -moz-background-size: cover;\r\n");
      out.write("\t        -o-background-size: cover;\r\n");
      out.write("\t        background-size: cover;\r\n");
      out.write("\t  \t\tposition : fixed;\r\n");
      out.write("\t  \t\ttop : 50px;\r\n");
      out.write("\t  \t\tleft : 450px;\r\n");
      out.write("\t \t\twidth : 1040px;\r\n");
      out.write("\t  \t\theight : 600px;\r\n");
      out.write("\t  \t\tborder : none;\r\n");
      out.write("\t  \t\tbackground-color : #FBF8EF;\r\n");
      out.write("\t  \t\tpadding-top: 8px;\r\n");
      out.write("\t        padding-bottom: 15px;\r\n");
      out.write("\t        padding-left : 8px;\r\n");
      out.write("\t        padding-right : 8px;\r\n");
      out.write("\t\t\tborder-radius: 15px;    \r\n");
      out.write("\t        -moz-border-radius: 15px;    \r\n");
      out.write("\t        -webkit-border-radius: 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t.form {\r\n");
      out.write("\t\t  position: relative;\r\n");
      out.write("\t\t  z-index: 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t.form button {\r\n");
      out.write("\t\t  font-family: \"Roboto\", sans-serif;\r\n");
      out.write("\t\t  /* 배경색 */\r\n");
      out.write("\t\t  background: #ff7f00 ;\r\n");
      out.write("\t\t  /* 아래로 글자가사리지지 않음 */\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t  border: 0;\r\n");
      out.write("\t\t  padding: 15px;\r\n");
      out.write("\t\t  /*글씨체 색깔 */\r\n");
      out.write("\t\t  color: #FFFFFF;\r\n");
      out.write("\t\t  font-size: 14px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.form_caja {\r\n");
      out.write("\t\t\twidth: 500px;\r\n");
      out.write("\t        padding-top: 8px;\r\n");
      out.write("\t        padding-bottom: 15px;\r\n");
      out.write("\t        padding-left : 8px;\r\n");
      out.write("\t        padding-right : 8px;\r\n");
      out.write("\t        margin: 0 auto 20px auto;\r\n");
      out.write("\t        background-color: #FF8C00;    \r\n");
      out.write("\t        border-radius: 15px;    \r\n");
      out.write("\t        -moz-border-radius: 15px;    \r\n");
      out.write("\t        -webkit-border-radius: 15px;\r\n");
      out.write("\t        color: #FF8C00;\r\n");
      out.write("\t        position:fixed center;\r\n");
      out.write("\t        overflow:hidden;\r\n");
      out.write("\t        position : fixed;\r\n");
      out.write("\t        top : 50px;\r\n");
      out.write("\t\t\tleft : 450px;\r\n");
      out.write("\t  \t\twidth : 1040px;\r\n");
      out.write("\t  \t\theight : 600px;\r\n");
      out.write("\t  \t\tborder :3px solid #FFFFFF;\r\n");
      out.write("\t    }\r\n");
      out.write("\t \r\n");
      out.write("\t    table { \r\n");
      out.write("\t    \tbackground-color : #FBF8EF; \r\n");
      out.write("\t    \tcolor : #000000; \r\n");
      out.write("\t    \talign:center; \r\n");
      out.write("\t    \theight : 200px; \r\n");
      out.write("\t    \ttop : 50px;\r\n");
      out.write("\t  \t\tleft : 450px;\r\n");
      out.write("\t  \t\twidth : 1040px;\r\n");
      out.write("\t  \t\theight : 600px;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    thead { \r\n");
      out.write("\t    \tbackground-color: #FFDAB9; \r\n");
      out.write("\t    \tcolor :#000000; \r\n");
      out.write("\t    \tpadding:4px; \r\n");
      out.write("\t    \tline-height:30px \r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t    th, td {\r\n");
      out.write("\t\t    padding: 10px;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t  \t\r\n");
      out.write("\t    tbody tr:nth-child(even) { background: #FBF8EF }\r\n");
      out.write("\t    tbody tr:nth-child(odd) { background: #FFF }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div style=\"border :1px solid none; width : 400px; height : 150px;\" class=\"form\">\r\n");
      out.write("\t\t\t<a href = \"main.jsp\"><img width = 400px height = 150px src = \"res/dgl.png\"></a>\r\n");
      out.write("\t\t\t<center> \r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t<img width = 45px height = 45px src = \"res/아코.png\">\r\n");
      out.write("\t\t\t\t");
      out.print((String)session.getAttribute("major") );
      out.write("과 \r\n");
      out.write("\t\t\t\t");
      out.print((String)session.getAttribute("name") );
      out.write(" \r\n");
      out.write("\t\t\t\t 님 환영합니다.\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<form style=\"display:none; overflow:hidden; position:realative\"><br><br>\r\n");
      out.write("\t\t\t \t<button type=\"button\" id=\"bbb1\" onclick=\"location.href='try.jsp' \" >수강신청 입력</button>\r\n");
      out.write("\t\t\t    <button type=\"button\" id=\"bbb2\" onclick=\"location.href='delete.jsp' \">수강신청 삭제</button>\r\n");
      out.write("\t\t\t    <button type=\"button\" onclick=\"location.href='check.jsp' \" style=\"background-color : #43A047\">수강신청 조회</button><br><br><br><br>\r\n");
      out.write("\t\t\t    <button type=\"button\" id=\"tip\">수강신청 유의사항</button>\r\n");
      out.write("\t\t\t    <br><br><Br><br>\r\n");
      out.write("\t\t\t    <button type=\"button\" id=\"bbb3\" onclick=\"location.href='info.jsp' \">마이페이지</button>\r\n");
      out.write("\t\t\t    <button type=\"button\" id=\"bbb4\" onclick=\"location.href='index.jsp' \">로그아웃</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		String Sid=(String)session.getAttribute("id");
		String []sid=new String[40];
		String []cid=new String[40];
		int i=0,i2=0;
		String []c_id=new String[40];
		String []c_name=new String[40];
		String []c_no=new String[40];
		int []c_unit=new int[40];
		Class.forName("oracle.jdbc.driver.OracleDriver");
		//Class.forName("org.mariadb.jdbc.Driver");
		
		try{
			 String url = "jdbc:oracle:thin:@127.0.0.1:1521:xe"; 
		// 2. DB와 연결  
		// String url = "jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8"; 
		//Connection conn = DriverManager.getConnection(url, "root", "staris"); 
		Connection conn = DriverManager.getConnection(url, "hr", "hrr"); 
		// 3. 쿼리를 전송할 Statement 객체를 생성
		Statement stmt = conn.createStatement();
		// 4. SQL문 입력(executeUpdate이용)
		String strSQL = "select c_id,s_id from enroll"; 
		PreparedStatement pstmt = conn.prepareStatement(strSQL); 
		ResultSet rs = pstmt.executeQuery();
		while(rs.next()) {
			sid[i]=rs.getString("s_id");
			
			cid[i]=rs.getString("c_id");
			i++;
			}
				
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 
			for (int j=0;j<i;j++){
				if(sid[j].equals(Sid)){
					
					 strSQL = "select c_id,c_name,c_id_no,c_unit from course where c_id=?"; 	
					 pstmt = conn.prepareStatement(strSQL); 
					 pstmt.setString(1,cid[j]);
					 
					 rs=pstmt.executeQuery();
					 while(rs.next()){
						 c_id[i2]=rs.getString("c_id");
						 c_name[i2]=rs.getString("c_name");
						 c_no[i2]=rs.getString("c_id_no");
						 c_unit[i2]=rs.getInt("c_unit");
						 i2++;
					 }
				}
			}	
		
      out.write(' ');
} 
		catch (SQLException e) { e.printStackTrace(); }
		 
      out.write("\r\n");
      out.write("\t\t<div class=\"form_caja\">\r\n");
      out.write("\t\t\t<table align=\"center\" style=\"overflow:hidden; position:realative\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>학수번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td>과목명</td>\r\n");
      out.write("\t\t\t\t\t\t<td>시간</td>\r\n");
      out.write("\t\t\t\t\t\t<td>학점</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 int unit=0;for(int k=0;k<i2;k++){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(c_id[k] );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(c_name[k] );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(c_no[k] );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(c_unit[k] );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
unit+=c_unit[k];} session.setAttribute("unit",unit);
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"fixed\" id=\"div2\" style=\"display:none\">\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t    <fieldset>\r\n");
      out.write("\t\t\t    \t<legend><h1>동국대학교 서울캠퍼스 수강신청 유의사항</h1></legend>\r\n");
      out.write("\t\t\t        <ul>\r\n");
      out.write("\t\t\t        \t<li>마일리지는 수강신청 가능 학점의 4배를 제공합니다.</li><br><br>\r\n");
      out.write("\t\t\t            <li>한 과목씩 마일리지를 베팅한 후, 과목옆에 있는 수강신청을 누르면 해당 수강과목신청이 완료됩니다.</li><br><br>\r\n");
      out.write("\t\t\t            <li>동일시간대의 교과목은 마일리지 베팅이 불가합니다.</li><br><br>\r\n");
      out.write("\t\t\t            <li>동시접속이 가능합니다.</li><br><br>\r\n");
      out.write("\t\t\t        </ul>\r\n");
      out.write("\t\t\t        <h3>마일리지를 적절히 배분하여 성공적인 수강신청이 될수있기를 바랍니다.</h3><br><br>\r\n");
      out.write("\t\t\t        <h4>담당자 : 김민선, 임성두, 최재원</h4><br>\r\n");
      out.write("\t\t\t    </fieldset>\r\n");
      out.write("\t\t    </center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
