/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-02-05 13:56:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("  * 동국대학교 베팅형 수강신청 \r\n");
      out.write("  * index.jsp\r\n");
      out.write("  * 수강신청 로그인 페이지\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>동국대학교 서울캠퍼스 수강신청</title>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t//alert(\"수강신청 성공을 기원합니다!\");\r\n");
      out.write("\t\t$(\"div\").show(\"slow\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t/* 배경화면을 꽉차게 설정 */\r\n");
      out.write("\t\thtml {\r\n");
      out.write("\t\t\tbackground: url(\"res/동국대학교.jpg\") no-repeat center center fixed;\r\n");
      out.write("\t\t    -webkit-background-size: cover;\r\n");
      out.write("\t\t    -moz-background-size: cover;\r\n");
      out.write("\t\t    -o-background-size: cover;\r\n");
      out.write("\t\t    background-size: cover;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t.login-page {\r\n");
      out.write("\t\t  width: 360px;\r\n");
      out.write("\t\t  padding: 7% 0 0;\r\n");
      out.write("\t\t  margin: auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.form {\r\n");
      out.write("\t\t  position: relative;\r\n");
      out.write("\t\t  z-index: 1;\r\n");
      out.write("\t\t  background: #FFFFFF;\r\n");
      out.write("\t\t  max-width: 360px;\r\n");
      out.write("\t\t  margin: 0 auto 100px;\r\n");
      out.write("\t\t  padding: 45px;\r\n");
      out.write("\t\t  text-align: center;\r\n");
      out.write("\t\t  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.form input {\r\n");
      out.write("\t\t  font-family: \"Roboto\", sans-serif;\r\n");
      out.write("\t\t  outline: 0;\r\n");
      out.write("\t\t  background: #f2f2f2;\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t  border: 0;\r\n");
      out.write("\t\t  margin: 0 0 15px;\r\n");
      out.write("\t\t  padding: 15px;\r\n");
      out.write("\t\t  box-sizing: border-box;\r\n");
      out.write("\t\t  font-size: 14px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.form button {\r\n");
      out.write("\t\t  font-family: \"Roboto\", sans-serif;\r\n");
      out.write("\t\t  text-transform: uppercase;\r\n");
      out.write("\t\t  outline: 0;\r\n");
      out.write("\t\t  background: #ff7f00 ;\r\n");
      out.write("\t\t  width: 100%;\r\n");
      out.write("\t\t  border: 0;\r\n");
      out.write("\t\t  padding: 15px;\r\n");
      out.write("\t\t  color: #FFFFFF;\r\n");
      out.write("\t\t  font-size: 14px;\r\n");
      out.write("\t\t  -webkit-transition: all 0.3 ease;\r\n");
      out.write("\t\t  transition: all 0.3 ease;\r\n");
      out.write("\t\t  cursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.form button:hover,.form button:active,.form button:focus {\r\n");
      out.write("\t\t  background: #43A047;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body> \r\n");
      out.write("\t\t<div><br><image width = 400px height = 150px src = \"res/동국대학교로고.png\" align = left><br>\r\n");
      out.write("\t\t<h1 align=center>동국대학교 서울캠퍼스 수강신청&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1></div>\r\n");
      out.write("\t  \t<div class=\"login-page\" >\r\n");
      out.write("\t  \t\t<div class=\"form\" style=\"display:none\">\r\n");
      out.write("\t  \t\t\t<form class=\"login-form\" action=\"/practiceweb/BoardServlet\" method=\"post\">\r\n");
      out.write("\t      \t\t\t<input type=\"text\" name =\"id\" placeholder=\"학번\"/>\r\n");
      out.write("\t      \t\t\t<input type=\"password\" name =\"pw\" placeholder=\"비밀번호\"/>\r\n");
      out.write("\t      \t\t\t<button type=\"submit\" value=\"login\" name = \"submit\">로그인</button>\r\n");
      out.write("\t   \t\t\t</form>\r\n");
      out.write("\t \t\t</div>\r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
