/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-02-05 13:57:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("  * 동국대학교 베팅형 수강신청 \r\n");
      out.write("  * check.jsp\r\n");
      out.write("  * 수강신청 메인 페이지\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>동국대학교 서울캠퍼스 수강신청</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("$(\"form\").show(\"slow\");\r\n");
      out.write("\r\n");
      out.write("$(\"#tip\").hover(function(){\r\n");
      out.write("  $(\"#div2\").show(\"slow\");\r\n");
      out.write("  $(\"#tip\").css('background-color', '#43A047');\r\n");
      out.write("\r\n");
      out.write("},function(){\r\n");
      out.write("  $(\"#div2\").slideUp(\"slow\");\r\n");
      out.write("  $(\"#tip\").css('background-color', '#ff7f00');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#bbb1\").hover(function(){\t  \r\n");
      out.write("\t  $(\"#bbb1\").css('background-color', '#43A047');\r\n");
      out.write("\t},function(){\t \r\n");
      out.write("\t  $(\"#bbb1\").css('background-color', '#ff7f00');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("$(\"#bbb2\").hover(function(){\t  \r\n");
      out.write("\t  $(\"#bbb2\").css('background-color', '#43A047');\r\n");
      out.write("\t},function(){\t \r\n");
      out.write("\t  $(\"#bbb2\").css('background-color', '#ff7f00');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("$(\"#bbb3\").hover(function(){\t  \r\n");
      out.write("\t  $(\"#bbb3\").css('background-color', '#43A047');\r\n");
      out.write("\t},function(){\t \r\n");
      out.write("\t  $(\"#bbb3\").css('background-color', '#ff7f00');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("$(\"#bbb4\").hover(function(){\t  \r\n");
      out.write("\t  $(\"#bbb4\").css('background-color', '#43A047');\r\n");
      out.write("\t},function(){\t \r\n");
      out.write("\t  $(\"#bbb4\").css('background-color', '#ff7f00');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("$(\"#bbb5\").hover(function(){\t  \r\n");
      out.write("\t  $(\"#bbb5\").css('background-color', '#43A047');\r\n");
      out.write("\t},function(){\t \r\n");
      out.write("\t  $(\"#bbb5\").css('background-color', '#ff7f00');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type = \"text/css\">\r\n");
      out.write("/* 배경화면을 꽉차게 설정 */\r\n");
      out.write("\thtml {\r\n");
      out.write("    \tbackground: url(\"res/background.gif\") no-repeat center center fixed;\r\n");
      out.write("        -webkit-background-size: cover;\r\n");
      out.write("        -moz-background-size: cover;\r\n");
      out.write("        -o-background-size: cover;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("  \tdiv.fixed {\r\n");
      out.write("\t\t-webkit-background-size: cover;\r\n");
      out.write("        -moz-background-size: cover;\r\n");
      out.write("        -o-background-size: cover;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("  \t\tposition : fixed;\r\n");
      out.write("  \t\ttop : 50px; \r\n");
      out.write("  \t\tleft : 450px;\r\n");
      out.write(" \t\twidth : 1040px;\r\n");
      out.write("  \t\theight : 600px;\r\n");
      out.write("  \t\tborder : none; \r\n");
      out.write("  \t\tbackground-color : #FBF8EF;\r\n");
      out.write("  \t\tpadding-top: 8px;\r\n");
      out.write("        padding-bottom: 15px;\r\n");
      out.write("        padding-left : 8px;\r\n");
      out.write("        padding-right : 8px;\r\n");
      out.write("   \t\tborder-radius: 15px;    \r\n");
      out.write("        -moz-border-radius: 15px;    \r\n");
      out.write("        -webkit-border-radius: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.form {\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  z-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.form button {\r\n");
      out.write("\t  font-family: \"Roboto\", sans-serif;\r\n");
      out.write("\t  /* 배경색 */\r\n");
      out.write("\t  background: #ff7f00 ;\r\n");
      out.write("\t  /* 아래로 글자가사리지지 않음 */\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  border: 0;\r\n");
      out.write("\t  padding: 15px;\r\n");
      out.write("\t  /*글씨체 색깔 */\r\n");
      out.write("\t  color: #FFFFFF;\r\n");
      out.write("\t  font-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.form_caja {\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t    padding-top: 8px;\r\n");
      out.write("\t    padding-bottom: 15px;\r\n");
      out.write("\t    padding-left : 8px;\r\n");
      out.write("\t    padding-right : 8px;\r\n");
      out.write("\t    margin: 0 auto 20px auto;\r\n");
      out.write("\t    background-color: #FF8C00;    \r\n");
      out.write("\t    border-radius: 15px;    \r\n");
      out.write("\t    -moz-border-radius: 15px;    \r\n");
      out.write("\t    -webkit-border-radius: 15px;\r\n");
      out.write("\t    color: #FF8C00;\r\n");
      out.write("\t    position:fixed center;\r\n");
      out.write("\t    overflow:hidden;\r\n");
      out.write("\t    position : fixed;\r\n");
      out.write("\t    top : 50px; \r\n");
      out.write("\t    left : 450px;\r\n");
      out.write("\t    width : 1040px;\r\n");
      out.write("\t    height : 600px;\r\n");
      out.write("\t    border :3px solid #FFFFFF;\r\n");
      out.write("\t    }\r\n");
      out.write(" \r\n");
      out.write("    table { background-color : #FBF8EF; color : #000000; align:center; }\r\n");
      out.write("    thead { background-color: #FFDAB9  ; color :#000000; padding:4px; line-height:30px }\r\n");
      out.write("    th, td {npadding: 10px; text-align: center; }\r\n");
      out.write("    tbody tr:nth-child(even) {background: #FBF8EF}\r\n");
      out.write("    tbody tr:nth-child(odd) {background: #FFF}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"border :1px solid none; width : 400px; height : 150px;\" class=\"form\">\r\n");
      out.write("\t<a href = \"main.jsp\"><img width = 400px height = 150px src = \"res/dgl.png\"></a>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<img width = 45px height = 45px src = \"res/아코.png\">\r\n");
      out.write("\t\t");
      out.print((String)session.getAttribute("major") );
      out.write("과 \r\n");
      out.write("\t\t");
      out.print((String)session.getAttribute("name") );
      out.write("님 환영합니다.\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t\t<form style=\"display:none\"><br><br>\r\n");
      out.write("\t    \t<button type=\"button\" id = \"bbb1\" onclick=\"location.href='try.jsp' \">수강신청 입력</button>\r\n");
      out.write("\t      \t<button type=\"button\" id = \"bbb2\" onclick=\"location.href='delete.jsp' \">수강신청 삭제</button>\r\n");
      out.write("\t      \t<button type=\"button\" id = \"bbb3\" onclick=\"location.href='check.jsp' \">수강신청 조회</button><br><br><br><br>\r\n");
      out.write("\t      \t<button type=\"button\" id=\"tip\">수강신청 유의사항</button><br><br><br><br>\r\n");
      out.write("\t      \t<button type=\"button\" id = \"bbb4\" onclick=\"location.href='info.jsp' \">마이페이지</button>\r\n");
      out.write("\t      \t<button type=\"button\" id = \"bbb5\" onclick=\"location.href='index.jsp' \">로그아웃</button>\r\n");
      out.write("\t    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fixed\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t    <h1>동국대학교 서울캠퍼스 수강신청</h1><br>\r\n");
      out.write("\t    <h3>2020학년도 1학기 수강신청</h3><br><br>\r\n");
      out.write("\t  \r\n");
      out.write("\t    <table  align=\"center\">\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t        \t<th rowspan=\"4\" bgcolor=\"#FFD954\">수강신청기간</th>\r\n");
      out.write("\t        \t<th bgcolor=\"#FFD3AE\">1학년</th>\r\n");
      out.write("\t        \t<td>2020년 2월 17일 월요일 09:00 ~ 2020년 2월 21일 금요일 23:59</td>\r\n");
      out.write("\t      \t</tr>\r\n");
      out.write("\t      \t<tr>\r\n");
      out.write("\t        \t<th bgcolor=\"#FFD3AE\">2학년</th>\r\n");
      out.write("\t        \t<td>2020년 2월 17일 월요일 09:00 ~ 2020년 2월 21일 금요일 23:59</td>\r\n");
      out.write("\t      \t</tr>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <th bgcolor=\"#FFD3AE\">3학년</th>\r\n");
      out.write("\t\t        <td>2020년 2월 17일 월요일 09:00 ~ 2020년 2월 21일 금요일 23:59</td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <th bgcolor=\"#FFD3AE\">4학년</th>\r\n");
      out.write("\t\t        <td>2020년 2월 17일 월요일 09:00 ~ 2020년 2월 21일 금요일 23:59</td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t         <tr>\r\n");
      out.write("\t\t        <th bgcolor=\"#E4B660\">수강정정기간</th>\r\n");
      out.write("\t\t        <td colspan=\"2\">2020년 3월 2일 월요일 09:00 ~ 2020년 3월 6일 금요일 23:59</td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <th bgcolor=\"#F2AB39\">수강취소기간</th>\r\n");
      out.write("\t\t        <td colspan=\"2\">2020년 3월 30일 월요일 09:00 ~ 2020년 4월 3일 금요일 23:59</td>\r\n");
      out.write("\t\t      </tr>  \r\n");
      out.write("\t\t</table><br><br><br>\r\n");
      out.write("\t    <h4>담당자 : 김민선, 임성두, 최재원</h4><br>\r\n");
      out.write("\t</center>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fixed\" id=\"div2\" style=\"display:none\">\r\n");
      out.write("\t<center>\r\n");
      out.write("    \t<fieldset>\r\n");
      out.write("    \t<legend><h1>동국대학교 서울캠퍼스 수강신청 유의사항</h1></legend>\r\n");
      out.write("    \t\t<ul>\r\n");
      out.write("        \t\t<li>마일리지는 수강신청 가능 학점의 4배를 제공합니다.</li><br><br>\r\n");
      out.write("            \t<li>한 과목씩 마일리지를 베팅한 후, 과목옆에 있는 수강신청을 누르면 해당 수강과목신청이 완료됩니다.</li><br><br>\r\n");
      out.write("            \t<li>동일시간대의 교과목은 마일리지 베팅이 불가합니다.</li><br><br>\r\n");
      out.write("            \t<li>동시접속이 가능합니다.</li><br><br>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("        \t<h3>마일리지를 적절히 배분하여 성공적인 수강신청이 될수있기를 바랍니다.</h3><br>\r\n");
      out.write("        \t<h4>담당자 : 김민선, 임성두, 최재원</h4><br>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</center>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
